apr.WebMVC/Models/ResponseResult.cs
using System.Collections.Generic;  namespace apr.WebMVC.Models {     public class ResponseResult<T>     {         private bool _state;         public bool State         {             get             {                 return (Items != null || Item != null) || _state;             }             set             {                 _state = value;             }         }         public string Message { get; set; }         public T Item { get; set; }         public List<T> Items { get; set; }     } }

apr.WebMVC/Controllers/ClienteController.cs
using apr.Business;
using apr.Entities;
using apr.WebMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace apr.WebMVC.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult findAll()
        {
            ResponseResult<Cliente> responseResult = new ResponseResult<Cliente>();

            try
            {
                responseResult.Items = new ClientesBll().findAll();
            }
            catch (Exception ex)
            {
                responseResult.Message = ex.Message;
            }

            return Json(responseResult, JsonRequestBehavior.AllowGet);
        }
    }
}

apr.WebMVC/Controllers/ExampleAjaxController.cs
using apr.Business;
using apr.Entities;
using apr.WebMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace apr.WebMVC.Controllers
{
    public class ExampleAjaxController : Controller
    {
        // GET: ExampleAjax
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult XMLHttpRequest()
        {
            return View();
        }

        public ActionResult FetchAPI()
        {
            return View();
        }

        public ActionResult FetchAPIAsync()
        {
            return View();
        }

    }
}

apr.WebMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace apr.WebMVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        
    }
}

apr.WebMVC/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using apr.Entities;
using apr.Business;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using apr.WebMVC.Models;

namespace apr.WebMVC.Controllers
{
    public class PedidoController : Controller
    {
        // GET: Pedido
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public JsonResult findAll()
        {
            ResponseResult<Pedido> responseResult = new ResponseResult<Pedido>();
            try
            {
                responseResult.Items = new PedidosBll().findAll();
            }
            catch (Exception ex)
            {
                responseResult.Message = ex.Message;
            }

            return Json(responseResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult create(Pedido pedido)
        {
            ResponseResult<Pedido> responseResult = new ResponseResult<Pedido>();

            try
            {
                responseResult.State = new PedidosBll().create(pedido);

                if (responseResult.State)
                    responseResult.Message = "Pedido Registrado correctamete";
                else
                    responseResult.Message = "El Registro de Pedido no Fue posible";
            }
            catch (Exception ex)
            {
                responseResult.Message = ex.Message;
            }

            return Json(responseResult, JsonRequestBehavior.AllowGet);
        }

    }
}

apr.WebMVC/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title - Web Cs & JS Vanilla</title>

    <!-- CSS -->
    <link href="@Url.Content("~")assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="@Url.Content("~")assets/vendor/fontawesome/css/all.min.css" rel="stylesheet" />
    @RenderSection("head", false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="#">.Net &  JS</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link active" })
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkAjax" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Example Ajax
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkAjax">
                            <li>
                                @Html.ActionLink("XMLHttpRequest", "XMLHttpRequest", "ExampleAjax", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Fetch API", "FetchAPI", "ExampleAjax", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Fetch API async", "FetchAPIAsync", "ExampleAjax", null, new { @class = "dropdown-item" })
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Categoria", "Index", "Categoria", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Producto", "Index", "Producto", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item active">
                        @Html.ActionLink("Pedido", "Index", "Pedido", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Others</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container pt-2 pb-5" id="app">

        @RenderBody()

    </div>

    <!-- JS -->
    <script src="@Url.Content("~")assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    @RenderSection("script", false)
</body>
</html>